### ISSUE TITLE
NIck's junk inside his trunk!?

### ISSUE THREAD

**Issue by starrodkirby86** [starrodkirby86/better-quiz-app#34]
NOTE:

MANY THINGS WERE LOST PLEASE RESCUE NICK'S POOR LOST ORPHANED CODE
WE DON'T KNOW WHAT HAPPENED TO IT
HERE ARE THE (ok caps lock off) following things that are lost:
--> move core -> loading
--> mulitple ans fix
--> options screen
--> title screen
--> loading scene
Label Options UI

you can check nick skeleton branch stuff for more details, unless it crashes your github like it does for him

godspeed

**Comment by starrodkirby86** [comment]
![](http://puu.sh/ldXNy/d50434303c.png) You see these little pea-like things? That's likely where those poor codes are stationed. Please rescue them.

**Comment by starrodkirby86** [comment]
oh yeah and uh the last question and the last binder aren't getting picked

so much for better quiz app

**Comment by starrodkirby86** [comment]
kk that's fixed, now comes rescuing nick's stuff

**Comment by NickWMorley** [comment]
Code was regenerated and merged back into master.

Have a nice day

**Comment by starrodkirby86** [comment]
no funny comment?

man you must be sick of it

thanks nick
